# helm/my-api-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          value: {{ .Values.env.DB_USER | quote }}
        - name: DB_PASSWORD
          value: {{ .Values.env.DB_PASSWORD | quote }}
        - name: DB_URL
          value: {{ .Values.env.DB_URL | quote }}
        - name: DB_PORT
          value: {{ .Values.env.DB_PORT | quote }}
        - name: DB_NAME
          value: {{ .Values.env.DB_NAME | quote }}
