image:
  repository: gcr.io/${PROJECT_ID}/board-game-api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 8080

env:
  DB_USER: ""
  DB_PASSWORD: ""
  DB_URL: ""
  DB_PORT: ""
  DB_NAME: ""
  PROJECT_ID: ""