image:
  repository: gcr.io/programma-me-lab01/board-game-api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 8080

env:
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_URL: "${DB_URL}"
  DB_PORT: "${DB_PORT}"
  DB_NAME: "${DB_NAME}"
  DB_HOST: "${DB_HOST}"
  PROJECT_ID: "${PROJECT_ID}"