apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-creator-binding
subjects:
- kind: ServiceAccount
  name: deploy-gke  # Nome da sua conta de serviço
  namespace: default  # Namespace onde a conta de serviço está localizada
roleRef:
  kind: ClusterRole
  name: role-creator
  apiGroup: rbac.authorization.k8s.io
