name: Deploy API to GKE

on:
  push:
    branches:
      - main  # Altere para o branch desejado
  workflow_dispatch:
    inputs:
      environment:
        description: Type the environment name that you want to deploy (dev, test ou prd)
        required: false
        default: development
env:
  environment: ${{github.event.inputs.environment || 'development'}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment || 'development'}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name:  Set Google Cloud Credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.SA_KEY}}

      - name: Configure Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v2

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Configure Docker to use the Google Cloud registry
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ vars.PROJECT_ID }}/board-game-api:latest .
          docker push gcr.io/${{ vars.PROJECT_ID }}/board-game-api:latest

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }}

      - name: Deploy with Helm
        image:
          repository: gcr.io/${{ vars.PROJECT_ID }}/board-game-api 
        env: 
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          REPO: gcr.io/${{ vars.PROJECT_ID }}/board-game-api
        run: |
          helm upgrade --install board-game-api ./helm/my-api-chart